coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        enabled: yes
        target: 90
        threshold: 5
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        enabled: yes
        target: 70

#parsers:
#  gcov:
#    branch_detection:
#      conditional: yes
#      loop: yes
#      method: yes
#      macro: no
